package com.ftoul.web.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.ftoul.util.webservice.WebserviceUtil;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * UserServiceService service = new UserServiceService();
 * UserService portType = service.getUserServicePort();
 * portType.checkUserExists(...);
 * </pre>
 * 
 * </p>
 * 
 */
public class UserServiceService extends Service {

	private final static URL USERSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ftoul.web.webservice.UserServiceService.class
					.getName());
	private static String wsdlLocation = WebserviceUtil.getWsdlLocation();
	private static String targetNamespace = WebserviceUtil.getTargetNamespace();
	private static String name = WebserviceUtil.getName();
	
	static {
		 URL url = null;
		 System.out.println(wsdlLocation+","+targetNamespace+","+name);
		try {
			URL baseUrl;
			baseUrl = com.ftoul.web.webservice.UserServiceService.class
					.getResource(".");
			url = new URL(baseUrl,wsdlLocation);
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: "+wsdlLocation+", retrying as a local file");
			logger.warning(e.getMessage());
		}
		USERSERVICESERVICE_WSDL_LOCATION = url;
	}

	public UserServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UserServiceService() {
		super(USERSERVICESERVICE_WSDL_LOCATION, new QName(targetNamespace,name));
	}

	/**
	 * 
	 * @return returns UserService
	 */
	@WebEndpoint(name = "UserServicePort")
	public UserService getUserServicePort() {
		return super.getPort(new QName(targetNamespace,name), UserService.class);
	}

}
