package com.ftoul.web.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://webservice.service.biz.member.mall.jq.com/")
public interface UserService {

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "checkUserExists", targetNamespace = "http://webservice.service.biz.member.mall.jq.com/", className = "com.ftoul.web.webservice.CheckUserExists")
	@ResponseWrapper(localName = "checkUserExistsResponse", targetNamespace = "http://webservice.service.biz.member.mall.jq.com/", className = "com.ftoul.web.webservice.CheckUserExistsResponse")
	public boolean checkUserExists(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "checkUser", targetNamespace = "http://webservice.service.biz.member.mall.jq.com/", className = "com.ftoul.web.webservice.CheckUser")
	@ResponseWrapper(localName = "checkUserResponse", targetNamespace = "http://webservice.service.biz.member.mall.jq.com/", className = "com.ftoul.web.webservice.CheckUserResponse")
	public String checkUser(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveUser", targetNamespace = "http://webservice.service.biz.member.mall.jq.com/", className = "com.ftoul.web.webservice.SaveUser")
	@ResponseWrapper(localName = "saveUserResponse", targetNamespace = "http://webservice.service.biz.member.mall.jq.com/", className = "com.ftoul.web.webservice.SaveUserResponse")
	public String saveUser(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 获取p2p用户可用蜂币余额
	 * @param 用户名
	 * @return p2p用户可用蜂币余额
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getIntegral", targetNamespace = "http://webservice.service.biz.member.mall.jq.com/", className = "com.ftoul.web.webservice.GetIntegral")
	@ResponseWrapper(localName = "getIntegralResponse", targetNamespace = "http://webservice.service.biz.member.mall.jq.com/", className = "com.ftoul.web.webservice.GetIntegralResponse")
	public Integer getIntegral(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "modifyPwd", targetNamespace = "http://webservice.service.biz.member.mall.jq.com/", className = "com.ftoul.web.webservice.ModifyPwd")
	@ResponseWrapper(localName = "modifyPwdResponse", targetNamespace = "http://webservice.service.biz.member.mall.jq.com/", className = "com.ftoul.web.webservice.ModifyPwdResponse")
	public boolean modifyPwd(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 修改p2p用户可用蜂币余额
	 * @param 用户名
	 * @param 修改的蜂币值
	 * @return returns boolean
	 */
	@WebMethod(operationName = "ModifyIntegral")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ModifyIntegral", targetNamespace = "http://webservice.service.biz.member.mall.jq.com/", className = "com.ftoul.web.webservice.ModifyIntegral")
	@ResponseWrapper(localName = "ModifyIntegralResponse", targetNamespace = "http://webservice.service.biz.member.mall.jq.com/", className = "com.ftoul.web.webservice.ModifyIntegralResponse")
	public boolean modifyIntegral(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Integer arg1);

}
